-- ==============================================================================
-- Migration: Create reservations table
-- Product Service - Inventory Reservation for Order Processing
-- ==============================================================================

-- Reservations table (tracks inventory holds for checkout)
CREATE TABLE IF NOT EXISTS product_service.reservations (
    id UUID PRIMARY KEY,  -- UUID v7 generated by application (time-sortable)
    status SMALLINT NOT NULL DEFAULT 0,  -- 0=PENDING, 1=CONFIRMED, 2=RELEASED, 3=EXPIRED
    items JSONB NOT NULL,                -- [{"sku_id": "...", "quantity": 2}, ...]
    expires_at TIMESTAMPTZ NOT NULL,     -- created_at + TTL (default 15 minutes)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Status must be valid
    CONSTRAINT chk_reservations_status CHECK (status >= 0 AND status <= 3)
);

-- Partial index for TTL worker: only PENDING reservations that need expiration check
CREATE INDEX IF NOT EXISTS idx_reservations_pending_expires
    ON product_service.reservations(expires_at)
    WHERE status = 0;  -- PENDING only

-- Index for status queries
CREATE INDEX IF NOT EXISTS idx_reservations_status
    ON product_service.reservations(status);

-- Index for created_at (time-based queries)
CREATE INDEX IF NOT EXISTS idx_reservations_created
    ON product_service.reservations(created_at);

COMMENT ON TABLE product_service.reservations IS 'Inventory reservations for TCC pattern';
COMMENT ON COLUMN product_service.reservations.id IS 'UUID v7 (time-sortable) for debugging';
COMMENT ON COLUMN product_service.reservations.status IS '0=PENDING, 1=CONFIRMED, 2=RELEASED, 3=EXPIRED';
COMMENT ON COLUMN product_service.reservations.items IS 'JSON array of {sku_id, quantity}';
COMMENT ON COLUMN product_service.reservations.expires_at IS 'Auto-release time (TTL)';
